name: Ofadiman's http request action
author: Ofadiman
description: Send http request to selected endpoint.
inputs:
  method:
    description: The HTTP method (get or options) used when sending request.
    required: true
  timeout:
    description: The maximum time (ms) to wait for a successful HTTP request.
    required: true
  url:
    description: The URL to which HTTP request will be sent.
    required: true
branding:
  color: purple
  icon: globe
runs:
  using: docker
  image: docker://ofadiman/http-request:39574361a8e297f753c472553a3bf9fd3e58b7fd
  args:
    - --method=${{ inputs.method}}
    - --url=${{ inputs.url}}
    - --timeout=${{ inputs.timeout}}
